/* ───────────────────────────────────────────────────────────
   generate-blur.mjs

   Walks public/images and produces a tiny base64 LQIP
   (low-quality image placeholder) for every photo, then writes
   src/lib/blur-map.ts — a path → data-URL map consumed by the
   <BlurImage> wrapper for Next.js `placeholder="blur"`.

   Run: `npm run gen:blur` (also runs automatically via `prebuild`).
   ─────────────────────────────────────────────────────────── */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, extname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const IMAGES_DIR = join(ROOT, "public", "images");
const OUT_FILE = join(ROOT, "src", "lib", "blur-map.ts");

/* Logos/icons are sharp-edged and tiny — a blur preview adds noise
   and bundle weight for no UX gain, so skip that directory. */
const EXCLUDED_DIRS = new Set(["logos"]);
const PHOTO_EXTS = new Set([".webp", ".jpg", ".jpeg", ".png", ".avif"]);

/** Recursively collect photo file paths under a directory. */
async function collectImages(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        return EXCLUDED_DIRS.has(entry.name) ? [] : collectImages(full);
      }
      return PHOTO_EXTS.has(extname(entry.name).toLowerCase()) ? [full] : [];
    }),
  );
  return files.flat();
}

/** Build a 16px-wide blurred WebP data URL for one image. */
async function lqip(absPath) {
  const buffer = await readFile(absPath);
  const out = await sharp(buffer)
    .resize(16, null, { fit: "inside", withoutEnlargement: true })
    .webp({ quality: 30 })
    .toBuffer();
  return `data:image/webp;base64,${out.toString("base64")}`;
}

async function main() {
  const images = (await collectImages(IMAGES_DIR)).sort();

  const map = {};
  for (const absPath of images) {
    /* Key = public URL path, e.g. "/images/sectors/power.webp" */
    const key = "/" + relative(join(ROOT, "public"), absPath).split(/[\\/]/).join("/");
    try {
      map[key] = await lqip(absPath);
    } catch (error) {
      console.warn(`[gen:blur] skipped ${key}: ${error.message}`);
    }
  }

  const body = Object.entries(map)
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join("\n");

  const file = `/* ─────────────────────────────────────────────────────────
   AUTO-GENERATED by scripts/generate-blur.mjs — DO NOT EDIT.
   Regenerate with \`npm run gen:blur\` after changing images.
   ───────────────────────────────────────────────────────── */

export const BLUR_MAP: Record<string, string> = {
${body}
};
`;

  await writeFile(OUT_FILE, file, "utf8");
  console.log(`[gen:blur] wrote ${Object.keys(map).length} placeholders → src/lib/blur-map.ts`);
}

main().catch((error) => {
  console.error("[gen:blur] failed:", error);
  process.exit(1);
});
